version: "3"

services:
  ros2_senai:
    build: .devcontainer
    command: 
      - /bin/bash
      - -c
      - |
        colcon build
        tail -f /dev/null
    
    environment:
      DISPLAY: $DISPLAY
      QT_GRAPHICSSYSTEM: "native"
     # LIBGL_ALWAYS_INDIRECT: 1
      XDG_RUNTIME_DIR: /tmp
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all

    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/home/ros/ros_ws/src   
      - /dev:/dev
